[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
trading-account = "3UhnNbUpRi1QM6szPYJce4tBNLCbjxMESJJ8touBd55h"
competition = "zQKpawEnbpdRj7MPzPuBKjJdgmSCC2A1aNi3NbGv4PN"
position = "8NHfJVx1ZD8tnb23v4xvTsUdhMxhHbjYpPz4ZDstobYP"
leaderboard = "5ohgmFUcN41uoZuP1QnFP9ErjDDCXA1FaxpFZAzfwU6q"
join-competition = "FFRL7nSQxFYMEcUxb912WsvbMSDMPNefdgCe4aZYNxWk"
open-position = "B1LMnYAtxvQLFG56YS9vscBFLid7KHp1nWTPYtFKFLPh"
close-position = "49kLMtwwnm5wdCKvtToUYgoxxo9PXjheS1rwcoSYkQfG"
settle-competition = "C1FTdtq531t4MViYtgo7LAft3GRkJimYAhVWFU4BE46i"

[programs.localnet]
trading-account = "3UhnNbUpRi1QM6szPYJce4tBNLCbjxMESJJ8touBd55h"
competition = "zQKpawEnbpdRj7MPzPuBKjJdgmSCC2A1aNi3NbGv4PN"
position = "8NHfJVx1ZD8tnb23v4xvTsUdhMxhHbjYpPz4ZDstobYP"
leaderboard = "5ohgmFUcN41uoZuP1QnFP9ErjDDCXA1FaxpFZAzfwU6q"
join-competition = "FFRL7nSQxFYMEcUxb912WsvbMSDMPNefdgCe4aZYNxWk"
open-position = "B1LMnYAtxvQLFG56YS9vscBFLid7KHp1nWTPYtFKFLPh"
close-position = "49kLMtwwnm5wdCKvtToUYgoxxo9PXjheS1rwcoSYkQfG"
settle-competition = "C1FTdtq531t4MViYtgo7LAft3GRkJimYAhVWFU4BE46i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "sleep 5 && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899