[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
paper_trading = "2zaegVL5odaCikNPEzCnaicgvu1n9ueHZoQrvEPWX161"

[programs.localnet]
paper_trading = "2zaegVL5odaCikNPEzCnaicgvu1n9ueHZoQrvEPWX161"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/phantom-wallet.json"

[workspace]
members = ["programs/contracts"]

[scripts]
test = "sleep 5 && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899